##
# Example Ansible playbook on deploying AskBot Django Application
#
# This installs PostgreSQL on an CentOS 7 system, creates a database called
# "askbotdb" and a user called "askbot" with password "123456"
# with access to the "askbotdb" database.
#

- hosts: webservers
  become: yes
  become_user: postgres
  gather_facts: no

  vars:
    dbname: askbotdb
    dbuser: askbot
    dbpassword: 123456

  tasks:
  - name: ensure database is created
    postgresql_db: name={{dbname}}

  - name: ensure user has access to database
    postgresql_user: db={{dbname}} name={{dbuser}} password={{dbpassword}} priv=ALL

  - name: ensure user does not have unnecessary privilege
    postgresql_user: name={{dbuser}} role_attr_flags=LOGIN

  - name: ensure no other user can access the database
    postgresql_privs: db={{dbname}} role={{dbuser}} type=database priv=ALL state=absent

- hosts: webservers
  become: yes
  become_user: root
  gather_facts: no

  tasks:
  - copy:
     src: pg_hba.conf
     dest: /var/lib/pgsql/data/
     owner: postgres
     group: postgres
     mode: 0644

  - systemd:
     name: postgresql.service
     state: restarted

  - copy:
     src: askbot_uwsgi.service
     dest: /etc/systemd/system/
     owner: root
     group: root
     mode: 0644

  - systemd:
     name: askbot_uwsgi.service
     state: restarted

- hosts: webservers
  become: yes
  become_user: vagrant
  gather_facts: no

  tasks:
   - name: installing askbot
     command: virtualenv askbot

   - pip:
      name: uwsgi
      virtualenv: /home/vagrant/askbot

   - pip:
      name:  psycopg2
      virtualenv: /home/vagrant/askbot

   - command: git clone https://github.com/ASKBOT/askbot-devel.git askbot/askbot-devel
     ignore_errors: True

   - command: /home/vagrant/askbot/bin/python setup.py develop
     args:
      chdir: askbot/askbot-devel/ 

   - command: /home/vagrant/askbot/bin/askbot-setup -n /home/vagrant/askbot/askbot-devel/ -e 1 -d askbotdb -u askbot -p 123456 
     # args:
     #  chdir: askbot/bin/ 

   - copy:
      src: settings.py
      dest: /home/vagrant/askbot/askbot-devel/
      owner: vagrant
      group: vagrant
      mode: 0644

   - command: /home/vagrant/askbot/bin/python manage.py syncdb --noinput
     args:
      chdir: askbot/askbot-devel/ 

   - command: /home/vagrant/askbot/bin/python manage.py collectstatic --noinput
     args:
      chdir: askbot/askbot-devel/

   - copy:
      src: askbot_uwsgi.ini
      dest: /home/vagrant/askbot/askbot-devel/
      owner: vagrant
      group: vagrant
      mode: 0644
#     notify: askbot uwsgi service

#  - name: starting uwsgi service

   # - copy:
   #    src: settings.py
   #    dest: /home/vagrant/askbot/askbot-devel/
   #    owner: vagrant
   #    group: vagrant
   #    mode: 0644

- hosts: webservers
  become: yes
  become_user: root
  gather_facts: no

  tasks:
  - systemd:
     name: askbot_uwsgi.service
     state: reloaded

  - name: starting askbot
    command: /home/vagrant/askbot/bin/python manage.py runserver 0.0.0.0:3031 
    args:
     chdir: askbot/askbot-devel/
